'use strict';
module.exports = {
    get: () => {
        return Promise.resolve({
            data: [
                {
                    "ticker_id": "AAAAA",
                    "name": "TALLINK GRUPP",
                    "employees": null,
                    "sector": "Transportation",
                    "industry": "Marine Shipping",
                    "financialsDaily": {
                        "ticker_id": "TAL1T",
                        "price": 0.662,
                        "div_yield": null,
                        "mkt_cap": 411308.0,
                        "p_e": 9.68,
                        "price_rev": 0.43,
                        "p_b": 0.4815,
                        "ev_ebitda": 8.01,
                        "ev": 1160000.0,
                        "chg": 0.0195,
                        "weekly_perf": -0.0063,
                        "monthly_perf": -0.3129,
                        "three_month_perf": -0.3485,
                        "six_month_perf": -0.3362,
                        "ytd_perf": -0.3566,
                        "yearly_perf": -0.3843,
                        "one_year_beta": 1.26,
                        "volatility": 0.0225
                    },
                    "financialsQuarterly": {
                        "ticker_id": "TAL1T",
                        "current_ratio": 0.51,
                        "debt_to_equity": 0.69,
                        "net_debt": 526584.0,
                        "quick_ratio": 0.36,
                        "assets": 1564000.0,
                        "debt": 564821.0,
                        "current_assets": 139767.0,
                        "eps_fy": 0.06,
                        "eps_ttm": 0.06,
                        "eps_diluted_ttm": 0.06,
                        "ebitda": 157691.0,
                        "gross_profit_mrq": 86682.0,
                        "gross_profit_fy": 175469.0,
                        "revenue": 949723.0,
                        "eps_diluted_fy": 0.06,
                        "annual_revenue": 949723.0,
                        "income": 40049.0,
                        "gross_mrq": 0.2027,
                        "operating_mrq": 0.0691,
                        "pretax_mrq": 0.0544,
                        "net_mrq": 0.0448,
                        "div_paid": -20096.0,
                        "div_per_share": 0.12,
                        "roa": 0.0274,
                        "roe": 0.0507,
                        "shares": 669882
                    }
                },
                {
                    "ticker_id": "TSM1T",
                    "name": "TALLINNA SADAM",
                    "employees": null,
                    "sector": "Transportation",
                    "industry": "Other Transportation",
                    "financialsDaily": {
                        "ticker_id": "TSM1T",
                        "price": 1.67,
                        "div_yield": 0.0859,
                        "mkt_cap": 410280.0,
                        "p_e": 9.36,
                        "price_rev": 3.14,
                        "p_b": 1.38,
                        "ev_ebitda": 9.39,
                        "ev": 694718.0,
                        "chg": 0.016,
                        "weekly_perf": 0.0292,
                        "monthly_perf": -0.168,
                        "three_month_perf": -0.2035,
                        "six_month_perf": -0.1954,
                        "ytd_perf": -0.2015,
                        "yearly_perf": -0.2696,
                        "one_year_beta": 1.04,
                        "volatility": 0.016
                    },
                    "financialsQuarterly": {
                        "ticker_id": "TSM1T",
                        "current_ratio": 1.48,
                        "debt_to_equity": 0.55,
                        "net_debt": 172663.0,
                        "quick_ratio": 1.47,
                        "assets": 625532.0,
                        "debt": 207846.0,
                        "current_assets": 46347.0,
                        "eps_fy": 0.17,
                        "eps_ttm": 0.17,
                        "eps_diluted_ttm": 0.17,
                        "ebitda": 73999.0,
                        "gross_profit_mrq": 8928.0,
                        "gross_profit_fy": 50963.0,
                        "revenue": 130536.0,
                        "eps_diluted_fy": 0.17,
                        "annual_revenue": 130536.0,
                        "income": 44404.0,
                        "gross_mrq": 0.4382,
                        "operating_mrq": 0.3904,
                        "pretax_mrq": 0.3825,
                        "net_mrq": 0.3402,
                        "div_paid": -34970.0,
                        "div_per_share": null,
                        "roa": 0.0711,
                        "roe": 0.1193,
                        "shares": 263000
                    }
                },
                {
                    "ticker_id": "TKM1T",
                    "name": "TALLINNA KAUBAMAJA GRUPP",
                    "employees": null,
                    "sector": "Retail Trade",
                    "industry": "Food Retail",
                    "financialsDaily": {
                        "ticker_id": "TKM1T",
                        "price": 7.66,
                        "div_yield": 0.0966,
                        "mkt_cap": 339682.0,
                        "p_e": 10.91,
                        "price_rev": 0.47,
                        "p_b": 1.59,
                        "ev_ebitda": 7.88,
                        "ev": 526185.0,
                        "chg": 0.0106,
                        "weekly_perf": -0.0821,
                        "monthly_perf": -0.1611,
                        "three_month_perf": -0.1556,
                        "six_month_perf": -0.0663,
                        "ytd_perf": -0.1461,
                        "yearly_perf": -0.1364,
                        "one_year_beta": 0.56,
                        "volatility": 0.016
                    },
                    "financialsQuarterly": {
                        "ticker_id": "TKM1T",
                        "current_ratio": 1.0,
                        "debt_to_equity": 0.9,
                        "net_debt": 163695.0,
                        "quick_ratio": 0.41,
                        "assets": 522313.0,
                        "debt": 204324.0,
                        "current_assets": 135838.0,
                        "eps_fy": 0.76,
                        "eps_ttm": 0.76,
                        "eps_diluted_ttm": 0.76,
                        "ebitda": 66783.0,
                        "gross_profit_mrq": 23752.0,
                        "gross_profit_fy": 83647.0,
                        "revenue": 717223.0,
                        "eps_diluted_fy": 0.76,
                        "annual_revenue": 717223.0,
                        "income": 31137.0,
                        "gross_mrq": 0.1127,
                        "operating_mrq": 0.0504,
                        "pretax_mrq": 0.0522,
                        "net_mrq": 0.0434,
                        "div_paid": -28917.0,
                        "div_per_share": 0.73,
                        "roa": 0.0667,
                        "roe": 0.1373,
                        "shares": 40729
                    }
                },
                {
                    "ticker_id": "LHV1T",
                    "name": "LHV GROUP",
                    "employees": 449,
                    "sector": "Finance",
                    "industry": "Financial Conglomerates",
                    "financialsDaily": {
                        "ticker_id": "LHV1T",
                        "price": 10.45,
                        "div_yield": 0.0197,
                        "mkt_cap": 274298.0,
                        "p_e": 10.71,
                        "price_rev": 2.84,
                        "p_b": 1.7,
                        "ev_ebitda": -19.04,
                        "ev": -816729.0,
                        "chg": 0.0633,
                        "weekly_perf": 0.0354,
                        "monthly_perf": -0.2176,
                        "three_month_perf": -0.1598,
                        "six_month_perf": -0.1458,
                        "ytd_perf": -0.1458,
                        "yearly_perf": -0.042,
                        "one_year_beta": 1.23,
                        "volatility": 0.0676
                    },
                    "financialsQuarterly": {
                        "ticker_id": "LHV1T",
                        "current_ratio": 0.0,
                        "debt_to_equity": 0.49,
                        "net_debt": -1171000.0,
                        "quick_ratio": null,
                        "assets": 3032000.0,
                        "debt": 100643.0,
                        "current_assets": null,
                        "eps_fy": 0.91,
                        "eps_ttm": 0.92,
                        "eps_diluted_ttm": 0.9,
                        "ebitda": 42163.0,
                        "gross_profit_mrq": 18528.0,
                        "gross_profit_fy": 69422.0,
                        "revenue": 98612.0,
                        "eps_diluted_fy": 0.89,
                        "annual_revenue": 98612.0,
                        "income": 24797.0,
                        "gross_mrq": 0.7074,
                        "operating_mrq": 0.3179,
                        "pretax_mrq": 0.3179,
                        "net_mrq": 0.2515,
                        "div_paid": -5463.0,
                        "div_per_share": 0.19,
                        "roa": 0.0105,
                        "roe": 0.1399,
                        "shares": 28454
                    }
                },
                {
                    "ticker_id": "TVEAT",
                    "name": "TALLINNA VESI",
                    "employees": 325,
                    "sector": "Utilities",
                    "industry": "Water Utilities",
                    "financialsDaily": {
                        "ticker_id": "TVEAT",
                        "price": 11.75,
                        "div_yield": 0.0644,
                        "mkt_cap": 233000.0,
                        "p_e": 8.39,
                        "price_rev": 3.67,
                        "p_b": 2.03,
                        "ev_ebitda": 6.77,
                        "ev": 261764.0,
                        "chg": -0.0043,
                        "weekly_perf": -0.0128,
                        "monthly_perf": -0.0413,
                        "three_month_perf": 0.0043,
                        "six_month_perf": 0.0642,
                        "ytd_perf": -0.0085,
                        "yearly_perf": 0.0741,
                        "one_year_beta": 0.51,
                        "volatility": 0.0086
                    },
                    "financialsQuarterly": {
                        "ticker_id": "TVEAT",
                        "current_ratio": 5.48,
                        "debt_to_equity": 0.8,
                        "net_debt": 27764.0,
                        "quick_ratio": 5.44,
                        "assets": 262855.0,
                        "debt": 92539.0,
                        "current_assets": 72518.0,
                        "eps_fy": 1.39,
                        "eps_ttm": 1.39,
                        "eps_diluted_ttm": 1.39,
                        "ebitda": 34025.0,
                        "gross_profit_mrq": 7796.0,
                        "gross_profit_fy": 33264.0,
                        "revenue": 63423.0,
                        "eps_diluted_fy": 1.39,
                        "annual_revenue": 63423.0,
                        "income": 27760.0,
                        "gross_mrq": 0.5245,
                        "operating_mrq": 0.4402,
                        "pretax_mrq": 0.4936,
                        "net_mrq": 0.4377,
                        "div_paid": -14965.0,
                        "div_per_share": null,
                        "roa": 0.1083,
                        "roe": 0.2543,
                        "shares": 20000
                    }
                },
                {
                    "ticker_id": "MRK1T",
                    "name": "MERKO EHITUS",
                    "employees": null,
                    "sector": "Industrial Services",
                    "industry": "Engineering & Construction",
                    "financialsDaily": {
                        "ticker_id": "MRK1T",
                        "price": 7.4,
                        "div_yield": 0.0912,
                        "mkt_cap": 116466.0,
                        "p_e": 7.16,
                        "price_rev": 0.36,
                        "p_b": 1.27,
                        "ev_ebitda": 10.78,
                        "ev": 209220.0,
                        "chg": 0.0578,
                        "weekly_perf": -0.0029,
                        "monthly_perf": -0.2564,
                        "three_month_perf": -0.2825,
                        "six_month_perf": -0.2418,
                        "ytd_perf": -0.258,
                        "yearly_perf": -0.2998,
                        "one_year_beta": 1.08,
                        "volatility": 0.0571
                    },
                    "financialsQuarterly": {
                        "ticker_id": "MRK1T",
                        "current_ratio": 2.44,
                        "debt_to_equity": 0.47,
                        "net_debt": 38977.0,
                        "quick_ratio": 0.76,
                        "assets": 281827.0,
                        "debt": 63726.0,
                        "current_assets": 241492.0,
                        "eps_fy": 0.92,
                        "eps_ttm": 0.92,
                        "eps_diluted_ttm": 0.92,
                        "ebitda": 20053.0,
                        "gross_profit_mrq": 13924.0,
                        "gross_profit_fy": 34821.0,
                        "revenue": 326779.0,
                        "eps_diluted_fy": 0.92,
                        "annual_revenue": 326779.0,
                        "income": 16270.0,
                        "gross_mrq": 0.1099,
                        "operating_mrq": 0.0538,
                        "pretax_mrq": 0.0568,
                        "net_mrq": 0.0498,
                        "div_paid": -17772.0,
                        "div_per_share": null,
                        "roa": 0.059,
                        "roe": 0.1242,
                        "shares": 17700
                    }
                },
                {
                    "ticker_id": "HAE1T",
                    "name": "HARJU ELEKTER",
                    "employees": 791,
                    "sector": "Producer Manufacturing",
                    "industry": "Electrical Products",
                    "financialsDaily": {
                        "ticker_id": "HAE1T",
                        "price": 3.79,
                        "div_yield": 0.05,
                        "mkt_cap": 64041.0,
                        "p_e": 26.03,
                        "price_rev": 0.45,
                        "p_b": 1.11,
                        "ev_ebitda": 13.01,
                        "ev": 88898.0,
                        "chg": 0.0111,
                        "weekly_perf": 0.0028,
                        "monthly_perf": -0.1122,
                        "three_month_perf": -0.1839,
                        "six_month_perf": -0.1271,
                        "ytd_perf": -0.1354,
                        "yearly_perf": -0.2587,
                        "one_year_beta": 0.98,
                        "volatility": 0.0111
                    },
                    "financialsQuarterly": {
                        "ticker_id": "HAE1T",
                        "current_ratio": 1.46,
                        "debt_to_equity": 0.29,
                        "net_debt": 14328.0,
                        "quick_ratio": 0.88,
                        "assets": 107899.0,
                        "debt": 19206.0,
                        "current_assets": 48012.0,
                        "eps_fy": 0.14,
                        "eps_ttm": 0.14,
                        "eps_diluted_ttm": 0.14,
                        "ebitda": 6827.0,
                        "gross_profit_mrq": 3995.0,
                        "gross_profit_fy": 17356.0,
                        "revenue": 143397.0,
                        "eps_diluted_fy": 0.14,
                        "annual_revenue": 143397.0,
                        "income": 2460.0,
                        "gross_mrq": 0.1272,
                        "operating_mrq": 0.0231,
                        "pretax_mrq": 0.0222,
                        "net_mrq": 0.0172,
                        "div_paid": -3193.0,
                        "div_per_share": null,
                        "roa": 0.0239,
                        "roe": 0.0367,
                        "shares": 17740
                    }
                },
                {
                    "ticker_id": "PKG1T",
                    "name": "PRO KAPITAL GRUPP",
                    "employees": null,
                    "sector": "Finance",
                    "industry": "Real Estate Development",
                    "financialsDaily": {
                        "ticker_id": "PKG1T",
                        "price": 0.74,
                        "div_yield": null,
                        "mkt_cap": 38264.0,
                        "p_e": null,
                        "price_rev": 0.69,
                        "p_b": 1.11,
                        "ev_ebitda": 21.74,
                        "ev": 191237.0,
                        "chg": 0.0074,
                        "weekly_perf": -0.0423,
                        "monthly_perf": -0.3704,
                        "three_month_perf": -0.5108,
                        "six_month_perf": -0.4887,
                        "ytd_perf": -0.5108,
                        "yearly_perf": -0.5802,
                        "one_year_beta": 1.07,
                        "volatility": 0.0303
                    },
                    "financialsQuarterly": {
                        "ticker_id": "PKG1T",
                        "current_ratio": 0.0,
                        "debt_to_equity": 1.71,
                        "net_debt": 112014.0,
                        "quick_ratio": 0.0,
                        "assets": 210821.0,
                        "debt": 122630.0,
                        "current_assets": null,
                        "eps_fy": -0.47,
                        "eps_ttm": -0.47,
                        "eps_diluted_ttm": -0.47,
                        "ebitda": 9229.0,
                        "gross_profit_mrq": 4054.0,
                        "gross_profit_fy": 15749.0,
                        "revenue": 55353.0,
                        "eps_diluted_fy": -0.47,
                        "annual_revenue": 55353.0,
                        "income": -26915.0,
                        "gross_mrq": 0.285,
                        "operating_mrq": -0.0887,
                        "pretax_mrq": -0.5263,
                        "net_mrq": -0.4863,
                        "div_paid": null,
                        "div_per_share": null,
                        "roa": -0.1181,
                        "roe": -0.3179,
                        "shares": 56688
                    }
                },
                {
                    "ticker_id": "NCN1T",
                    "name": "NORDECON",
                    "employees": null,
                    "sector": "Industrial Services",
                    "industry": "Engineering & Construction",
                    "financialsDaily": {
                        "ticker_id": "NCN1T",
                        "price": 0.875,
                        "div_yield": null,
                        "mkt_cap": 26484.0,
                        "p_e": 7.45,
                        "price_rev": 0.11,
                        "p_b": 0.86,
                        "ev_ebitda": null,
                        "ev": null,
                        "chg": 0.0364,
                        "weekly_perf": 0.024,
                        "monthly_perf": -0.2083,
                        "three_month_perf": -0.1699,
                        "six_month_perf": -0.1186,
                        "ytd_perf": -0.1699,
                        "yearly_perf": -0.1094,
                        "one_year_beta": 1.11,
                        "volatility": 0.0788
                    },
                    "financialsQuarterly": {
                        "ticker_id": "NCN1T",
                        "current_ratio": 1.01,
                        "debt_to_equity": 0.84,
                        "net_debt": 20352.0,
                        "quick_ratio": 0.68,
                        "assets": 118601.0,
                        "debt": 27384.0,
                        "current_assets": 68503.0,
                        "eps_fy": 0.11,
                        "eps_ttm": 0.11,
                        "eps_diluted_ttm": 0.11,
                        "ebitda": null,
                        "gross_profit_mrq": 4042.0,
                        "gross_profit_fy": 11763.0,
                        "revenue": 233508.0,
                        "eps_diluted_fy": 0.11,
                        "annual_revenue": 233508.0,
                        "income": 3367.0,
                        "gross_mrq": 0.0592,
                        "operating_mrq": 0.0177,
                        "pretax_mrq": 0.0185,
                        "net_mrq": 0.0144,
                        "div_paid": -2360.0,
                        "div_per_share": null,
                        "roa": 0.0302,
                        "roe": 0.1084,
                        "shares": 31529
                    }
                },
                {
                    "ticker_id": "EEG1T",
                    "name": "EKSPRESS GRUPP",
                    "employees": null,
                    "sector": "Consumer Services",
                    "industry": "Publishing: Books/Magazines",
                    "financialsDaily": {
                        "ticker_id": "EEG1T",
                        "price": 0.62,
                        "div_yield": null,
                        "mkt_cap": 19208.0,
                        "p_e": 13.78,
                        "price_rev": 0.28,
                        "p_b": 0.48,
                        "ev_ebitda": 7.16,
                        "ev": 45363.0,
                        "chg": -0.0543,
                        "weekly_perf": 0.0,
                        "monthly_perf": -0.2651,
                        "three_month_perf": -0.2606,
                        "six_month_perf": -0.2179,
                        "ytd_perf": -0.2606,
                        "yearly_perf": -0.3679,
                        "one_year_beta": 0.8,
                        "volatility": 0.0932
                    },
                    "financialsQuarterly": {
                        "ticker_id": "EEG1T",
                        "current_ratio": 0.9,
                        "debt_to_equity": 0.47,
                        "net_debt": 20695.0,
                        "quick_ratio": 0.76,
                        "assets": 95407.0,
                        "debt": 24342.0,
                        "current_assets": 19472.0,
                        "eps_fy": 0.05,
                        "eps_ttm": 0.05,
                        "eps_diluted_ttm": 0.05,
                        "ebitda": 6332.0,
                        "gross_profit_mrq": 5025.0,
                        "gross_profit_fy": 11744.0,
                        "revenue": 67456.0,
                        "eps_diluted_fy": 0.05,
                        "annual_revenue": 67456.0,
                        "income": 1394.0,
                        "gross_mrq": 0.1988,
                        "operating_mrq": 0.0335,
                        "pretax_mrq": 0.0281,
                        "net_mrq": 0.0207,
                        "div_paid": null,
                        "div_per_share": null,
                        "roa": 0.0162,
                        "roe": 0.0273,
                        "shares": 29779
                    }
                },
                {
                    "ticker_id": "ARC1T",
                    "name": "ARCO VARA",
                    "employees": null,
                    "sector": "Finance",
                    "industry": "Real Estate Development",
                    "financialsDaily": {
                        "ticker_id": "ARC1T",
                        "price": 1.03,
                        "div_yield": 0.0105,
                        "mkt_cap": 8683.0,
                        "p_e": 25.87,
                        "price_rev": 0.69,
                        "p_b": 0.77,
                        "ev_ebitda": 21.62,
                        "ev": 22381.0,
                        "chg": 0.0521,
                        "weekly_perf": 0.0521,
                        "monthly_perf": -0.1721,
                        "three_month_perf": -0.1368,
                        "six_month_perf": -0.0472,
                        "ytd_perf": -0.114,
                        "yearly_perf": -0.1062,
                        "one_year_beta": 1.23,
                        "volatility": 0.1204
                    },
                    "financialsQuarterly": {
                        "ticker_id": "ARC1T",
                        "current_ratio": 0.0,
                        "debt_to_equity": 0.93,
                        "net_debt": 11450.0,
                        "quick_ratio": null,
                        "assets": 28754.0,
                        "debt": 12320.0,
                        "current_assets": null,
                        "eps_fy": 0.04,
                        "eps_ttm": 0.04,
                        "eps_diluted_ttm": 0.04,
                        "ebitda": 1084.0,
                        "gross_profit_mrq": 1451.0,
                        "gross_profit_fy": 1921.0,
                        "revenue": 13246.0,
                        "eps_diluted_fy": 0.04,
                        "annual_revenue": 13246.0,
                        "income": 388.0,
                        "gross_mrq": 0.1557,
                        "operating_mrq": 0.0289,
                        "pretax_mrq": 0.0289,
                        "net_mrq": 0.0289,
                        "div_paid": -90.0,
                        "div_per_share": null,
                        "roa": 0.0125,
                        "roe": 0.0298,
                        "shares": 8998
                    }
                },
                {
                    "ticker_id": "BLT1T",
                    "name": "BALTIKA",
                    "employees": null,
                    "sector": "Consumer Non-Durables",
                    "industry": "Apparel/Footwear",
                    "financialsDaily": {
                        "ticker_id": "BLT1T",
                        "price": 0.098,
                        "div_yield": null,
                        "mkt_cap": 5300.0,
                        "p_e": null,
                        "price_rev": 0.13,
                        "p_b": 4.4764,
                        "ev_ebitda": 6.74,
                        "ev": 29035.0,
                        "chg": -0.006,
                        "weekly_perf": 0.0421,
                        "monthly_perf": -0.1951,
                        "three_month_perf": -0.2721,
                        "six_month_perf": -0.2326,
                        "ytd_perf": -0.2667,
                        "yearly_perf": -0.8783,
                        "one_year_beta": 0.82,
                        "volatility": 0.0081
                    },
                    "financialsQuarterly": {
                        "ticker_id": "BLT1T",
                        "current_ratio": 0.76,
                        "debt_to_equity": 18.29,
                        "net_debt": 21734.0,
                        "quick_ratio": 0.08,
                        "assets": 27319.0,
                        "debt": 21998.0,
                        "current_assets": 8557.0,
                        "eps_fy": -0.16,
                        "eps_ttm": -0.33,
                        "eps_diluted_ttm": -0.33,
                        "ebitda": 4699.0,
                        "gross_profit_mrq": 2963.0,
                        "gross_profit_fy": 12893.0,
                        "revenue": 39711.0,
                        "eps_diluted_fy": -0.16,
                        "annual_revenue": 39711.0,
                        "income": -5909.0,
                        "gross_mrq": 0.3247,
                        "operating_mrq": -0.0739,
                        "pretax_mrq": -0.1486,
                        "net_mrq": -0.1488,
                        "div_paid": null,
                        "div_per_share": null,
                        "roa": -0.2792,
                        "roe": -9.3039,
                        "shares": 54080
                    }
                },
                {
                    "ticker_id": "CPA1T",
                    "name": "COOP PANK",
                    "employees": null,
                    "sector": "Finance",
                    "industry": "Regional Banks",
                    "financialsDaily": {
                        "ticker_id": "CPA1T",
                        "price": 0.973,
                        "div_yield": null,
                        "mkt_cap": 101000.0,
                        "p_e": 15.78,
                        "price_rev": 3.89,
                        "p_b": 1.54,
                        "ev_ebitda": null,
                        "ev": null,
                        "chg": 0.01994,
                        "weekly_perf": 0.003728606,
                        "monthly_perf": -0.235938959,
                        "three_month_perf": -0.254886365,
                        "six_month_perf": -0.204826025,
                        "ytd_perf": -0.24482,
                        "yearly_perf": -0.31947115,
                        "one_year_beta": 1.11,
                        "volatility": 0.0503837
                    },
                    "financialsQuarterly": {
                        "ticker_id": "CPA1T",
                        "current_ratio": 0.0,
                        "debt_to_equity": 0.0,
                        "net_debt": null,
                        "quick_ratio": null,
                        "assets": 446280.0,
                        "debt": null,
                        "current_assets": null,
                        "eps_fy": null,
                        "eps_ttm": null,
                        "eps_diluted_ttm": null,
                        "ebitda": null,
                        "gross_profit_mrq": null,
                        "gross_profit_fy": null,
                        "revenue": 19900.0,
                        "eps_diluted_fy": 0.05,
                        "annual_revenue": 19900.0,
                        "income": null,
                        "gross_mrq": null,
                        "operating_mrq": null,
                        "pretax_mrq": null,
                        "net_mrq": 0.2389,
                        "div_paid": null,
                        "div_per_share": null,
                        "roa": 0.0116,
                        "roe": 0.1008,
                        "shares": 89456
                    }
                },
                {
                    "ticker_id": "EFT1T",
                    "name": "EFTEN REAL ESTATE FUND III",
                    "employees": 12,
                    "sector": "Miscellaneous",
                    "industry": "Investment Trusts/Mutual Funds",
                    "financialsDaily": {
                        "ticker_id": "EFT1T",
                        "price": 14.7,
                        "div_yield": 0.0693,
                        "mkt_cap": 76000.0,
                        "p_e": 6.68,
                        "price_rev": 5.45,
                        "p_b": 0.81,
                        "ev_ebitda": null,
                        "ev": null,
                        "chg": 0.01773,
                        "weekly_perf": 0.003316353,
                        "monthly_perf": -0.209852367,
                        "three_month_perf": -0.226704853,
                        "six_month_perf": -0.182179435,
                        "ytd_perf": -0.21775,
                        "yearly_perf": -0.28414882,
                        "one_year_beta": 0.99,
                        "volatility": 0.0448131
                    },
                    "financialsQuarterly": {
                        "ticker_id": "EFT1T",
                        "current_ratio": 0.0,
                        "debt_to_equity": 0.0,
                        "net_debt": null,
                        "quick_ratio": null,
                        "assets": 132830.0,
                        "debt": null,
                        "current_assets": null,
                        "eps_fy": null,
                        "eps_ttm": 2.05,
                        "eps_diluted_ttm": 2.05,
                        "ebitda": null,
                        "gross_profit_mrq": 9180.0,
                        "gross_profit_fy": null,
                        "revenue": 9510.0,
                        "eps_diluted_fy": 2.05,
                        "annual_revenue": 9510.0,
                        "income": 7740.0,
                        "gross_mrq": 0.9654,
                        "operating_mrq": null,
                        "pretax_mrq": null,
                        "net_mrq": 0.8134,
                        "div_paid": null,
                        "div_per_share": null,
                        "roa": 0.0641,
                        "roe": 0.1272,
                        "shares": 4222
                    }
                },
                {
                    "ticker_id": "PRF1T",
                    "name": "PRFOODS",
                    "employees": 345,
                    "sector": "Consumer Non-Durables",
                    "industry": "Food: Major Diversified",
                    "financialsDaily": {
                        "ticker_id": "PRF1T",
                        "price": 0.4,
                        "div_yield": null,
                        "mkt_cap": 14696.0,
                        "p_e": null,
                        "price_rev": 0.1743,
                        "p_b": 0.6914,
                        "ev_ebitda": 12.1007,
                        "ev": 35737.0,
                        "chg": 0.01747,
                        "weekly_perf": 0.003266667,
                        "monthly_perf": -0.206708333,
                        "three_month_perf": -0.223308333,
                        "six_month_perf": -0.17945,
                        "ytd_perf": -0.21449,
                        "yearly_perf": -0.27989167,
                        "one_year_beta": 0.97,
                        "volatility": 0.0441417
                    },
                    "financialsQuarterly": {
                        "ticker_id": "PRF1T",
                        "current_ratio": 0.8648,
                        "debt_to_equity": 0.8772,
                        "net_debt": 17770.0,
                        "quick_ratio": 0.3471,
                        "assets": 60493.0,
                        "debt": 20450.0,
                        "current_assets": null,
                        "eps_fy": -0.0387,
                        "eps_ttm": -0.0204,
                        "eps_diluted_ttm": -0.0204,
                        "ebitda": 3058.0,
                        "gross_profit_mrq": 4208.0,
                        "gross_profit_fy": 11429.0,
                        "revenue": 85727.0,
                        "eps_diluted_fy": -0.0387,
                        "annual_revenue": 85727.0,
                        "income": -1458.0,
                        "gross_mrq": 0.1279,
                        "operating_mrq": 0.0033,
                        "pretax_mrq": -0.0036,
                        "net_mrq": -0.009,
                        "div_paid": -377.0,
                        "div_per_share": null,
                        "roa": -0.012,
                        "roe": -0.0328,
                        "shares": 37683
                    }
                },
                {
                    "ticker_id": "SFG1T",
                    "name": "SILVANO FASHION GROUP",
                    "employees": null,
                    "sector": "Consumer Non-Durables",
                    "industry": "Apparel/Footwear",
                    "financialsDaily": {
                        "ticker_id": "SFG1T",
                        "price": 1.535,
                        "div_yield": 0.214286,
                        "mkt_cap": 50400.0,
                        "p_e": 4.6964,
                        "price_rev": 0.8851,
                        "p_b": 1.9146,
                        "ev_ebitda": 4.8218,
                        "ev": 85090.0,
                        "chg": 0.01892,
                        "weekly_perf": 0.003538522,
                        "monthly_perf": -0.223910808,
                        "three_month_perf": -0.241892276,
                        "six_month_perf": -0.194384008,
                        "ytd_perf": -0.23234,
                        "yearly_perf": -0.30318453,
                        "one_year_beta": 1.06,
                        "volatility": 0.0478152
                    },
                    "financialsQuarterly": {
                        "ticker_id": "SFG1T",
                        "current_ratio": 2.6722,
                        "debt_to_equity": 0.2923,
                        "net_debt": 3543.0,
                        "quick_ratio": 0.7649,
                        "assets": 46309.0,
                        "debt": 8695.0,
                        "current_assets": null,
                        "eps_fy": 0.3,
                        "eps_ttm": 0.2981,
                        "eps_diluted_ttm": 0.2981,
                        "ebitda": 7647.0,
                        "gross_profit_mrq": 6994.0,
                        "gross_profit_fy": 29651.0,
                        "revenue": 56943.0,
                        "eps_diluted_fy": 0.3,
                        "annual_revenue": 56943.0,
                        "income": 10663.0,
                        "gross_mrq": 0.5673,
                        "operating_mrq": 0.2345,
                        "pretax_mrq": 0.2666,
                        "net_mrq": 0.1873,
                        "div_paid": -7710.0,
                        "div_per_share": null,
                        "roa": 0.2323,
                        "roe": 0.3965,
                        "shares": 36000
                    }
                }
            ]
        });
    }
};